{"cells":[{"cell_type":"code","execution_count":1,"id":"d5b057db","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"d5b057db","executionInfo":{"status":"ok","timestamp":1681394758781,"user_tz":-540,"elapsed":18887,"user":{"displayName":"유승우","userId":"18267622456325964228"}},"outputId":"b1d50d02-4533-4a81-b6f2-6bfcb6c73c46"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","\n","drive.mount('/content/drive')\n","\n","# TODO: Enter the path in your Drive of the assignment.\n","# e.g. 'cs231n/assignments/assignment3/'\n","FOLDERNAME = '딥러닝/cs231n/assignments/assignment3/'\n","\n","assert FOLDERNAME is not None, \"[!] Enter the foldername.\""]},{"cell_type":"markdown","id":"23b8d1fb","metadata":{"id":"23b8d1fb"},"source":["# Collect Submission - Zip + Generate PDF \n","\n","<font color=\"red\">**Note:** Remember to execute ALL notebooks' cells before this step. We won't be regrading missing cell outputs.</font>\n","\n","Run this notebook once you have completed all the other notebooks.\n","\n","It will:\n","\n","* Generate a zip file of your code (`.py` and `.ipynb`) called `a3_code_submission.zip`.\n","* Convert all notebooks into a single PDF file called `a3_inline_submission.pdf`.\n","\n","If your submission for this step was successful, you should see the following display message:\n","\n","`### Done! Please submit a3_code_submission.zip and a3_inline_submission.pdf to Gradescope. ###`\n","\n","Make sure to download the zip and pdf file locally to your computer, then submit to Gradescope. Congrats on successfully completing the assignment!"]},{"cell_type":"code","execution_count":2,"id":"51308c91","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"51308c91","executionInfo":{"status":"ok","timestamp":1681394789824,"user_tz":-540,"elapsed":27483,"user":{"displayName":"유승우","userId":"18267622456325964228"}},"outputId":"4a4be244-d5b5-4a2c-bdbb-464eb82153d2"},"outputs":[{"output_type":"stream","name":"stdout","text":["/content/drive/My Drive/딥러닝/cs231n/assignments/assignment3\n","Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]\n","Get:2 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]\n","Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease\n","Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease\n","Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease\n","Get:6 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1,028 kB]\n","Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]\n","Hit:8 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease\n","Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,593 kB]\n","Hit:10 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease\n","Get:11 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]\n","Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease\n","Get:13 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,324 kB]\n","Hit:14 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal InRelease\n","Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3,075 kB]\n","Fetched 8,360 kB in 2s (4,303 kB/s)\n","Reading package lists... Done\n","Reading package lists... Done\n","Building dependency tree       \n","Reading state information... Done\n","E: Unable to locate package texlive-generic-recommended\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting PyPDF2\n","  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m232.6/232.6 kB\u001b[0m \u001b[31m6.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: typing_extensions>=3.10.0.0 in /usr/local/lib/python3.9/dist-packages (from PyPDF2) (4.5.0)\n","Installing collected packages: PyPDF2\n","Successfully installed PyPDF2-3.0.1\n","### Zipping file ###\n","### Creating PDFs ###\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF RNN_Captioning.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF Transformer_Captioning.ipynb.\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/jupyter-nbconvert\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.9/dist-packages/jupyter_core/application.py\", line 277, in launch_instance\n","    return super().launch_instance(argv=argv, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n","    app.start()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 423, in start\n","    self.convert_notebooks()\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 597, in convert_notebooks\n","    self.convert_single_notebook(notebook_filename)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 560, in convert_single_notebook\n","    output, resources = self.export_single_notebook(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/nbconvertapp.py\", line 488, in export_single_notebook\n","    output, resources = self.exporter.from_filename(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 189, in from_filename\n","    return self.from_file(f, resources=resources, **kw)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/exporter.py\", line 206, in from_file\n","    return self.from_notebook_node(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 194, in from_notebook_node\n","    self.run_latex(tex_file)\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 164, in run_latex\n","    return self.run_command(\n","  File \"/usr/local/lib/python3.9/dist-packages/nbconvert/exporters/pdf.py\", line 111, in run_command\n","    raise OSError(\n","OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n","Created PDF Generative_Adversarial_Networks.ipynb.\n","Traceback (most recent call last):\n","  File \"/content/drive/My Drive/딥러닝/cs231n/assignments/assignment3/makepdf.py\", line 45, in <module>\n","    main(args.notebooks, args.pdf_filename)\n","  File \"/content/drive/My Drive/딥러닝/cs231n/assignments/assignment3/makepdf.py\", line 29, in main\n","    merger = PdfFileMerger()\n","  File \"/usr/local/lib/python3.9/dist-packages/PyPDF2/_merger.py\", line 817, in __init__\n","    deprecation_with_replacement(\"PdfFileMerger\", \"PdfMerger\", \"3.0.0\")\n","  File \"/usr/local/lib/python3.9/dist-packages/PyPDF2/_utils.py\", line 369, in deprecation_with_replacement\n","    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))\n","  File \"/usr/local/lib/python3.9/dist-packages/PyPDF2/_utils.py\", line 351, in deprecation\n","    raise DeprecationError(msg)\n","PyPDF2.errors.DeprecationError: PdfFileMerger is deprecated and was removed in PyPDF2 3.0.0. Use PdfMerger instead.\n"]}],"source":["%cd /content/drive/My\\ Drive/$FOLDERNAME\n","!sudo apt-get update\n","!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended\n","!pip install PyPDF2\n","!bash collectSubmission.sh"]}],"metadata":{"colab":{"provenance":[]},"language_info":{"name":"python"},"kernelspec":{"name":"python3","display_name":"Python 3"},"gpuClass":"standard"},"nbformat":4,"nbformat_minor":5}